[tools]
python = "3.12"
node = "latest"
neovim = "latest"
gh = "latest"
jq = "latest"
jless = "latest"
dust = "latest"
aws = "latest"
fd = "latest"
k9s = "latest"
npm = "latest"
duf = "latest"
fzf = "latest"
zoxide = "latest"
ghorg = "latest"

[settings]
idiomatic_version_file_enable_tools = []
