[tools]
python = "3.13"
node = "latest"
neovim = "latest"
gh = "latest"
jq = "latest"
jless = "latest"
dust = "latest"
aws = "latest"
fd = "latest"
k9s = "latest"
npm = "latest"
duf = "latest"
fzf = "latest"
zoxide = "latest"
bat = "latest"
lua-language-server = "latest"
uv = "latest"
stylua = "latest"
starship = "latest"
tmux = "latest"
fastfetch = "latest"
yt-dlp = "latest"

[settings]
idiomatic_version_file_enable_tools = []
